growingio/growingio-sdk-docs

docs/What's New.md

version 3.2.1

---

docs/miniprogranm/base/gettingStarted.md

feat: 添加小程序taro3集成方式

---

.gitignore
docs/server/Java SDK.md

修正Java SDK用户融合api 名称错误
无
Java SDK 接口名称修正
无

fix(java sdk.md): fix interface name

---

docs/android/version.md
github_version_fetch.py

更新日志中仅显示正式版本，Github的Release中保留hotfix版本
github_version_fetch.py 脚本执行后，仅更新正式版本
版本更新脚本 github_version_fetch.py
无

build: 更新日志仅展示正式版本

---

docs/ios/base/Configuration.md
docs/ios/develop/custom_sdk.md
docs/ios/version.md

添加iOS SDK 3.3.2 版本更新内容，修改相关文档
无
无
无

feat: iOS SDK 3.3.2 版本更新内容

---

docs/miniprogram/commonlyApi.md
docs/webjs/base/getting_started.md
docs/webjs/plugins.md

https://growingio.atlassian.net/browse/PI-40662
添加web在初始化时不要在init和send直接调用用户信息相关接口的提示
修复小程序中gdp的表述
无
无
无

fix: 添加web初始化注意提醒，修复小程序变量名

---

docs/miniprogram/commonlyApi.md
src/css/custom.css

修复小程序与h5打通时参数更新demo
修复menu样式
无
无
无

fix: 修复与h5打通时demo及样式

---

docs/miniprogram/initSettings.md
docs/webjs/plugins.md

fix:  增加extraParams 和ignoreFields 配置代码示例
无
小程序SDK extraParams 和 ignoreFields 的使用
无

fix:  增加extraParams 和ignoreFields 配置代码示例

---

docs/android/base/Configuration.md
docs/android/base/Getting Started.md
docs/android/develop/coutom sdk.md
docs/android/develop/custom module.md
docs/android/question.md
docs/android/version.md
docs/giokit/android/version.md
docs/ios/base/Configuration.md
docs/ios/develop/custom_sdk.md
docs/ios/version.md
version_config.json

docs: 更新 iOS/Android SDK 3.3.3 版本记录
无
无
无

docs: 更新 iOS/Android SDK 3.3.3 版本记录

---

docs/compliance/_category_.json
docs/compliance/minpCompliance.md
docs/compliance/webCompliance.md
docusaurus.config.js
package-lock.json
package.json
src/css/custom.css

fix: 1. 增加帮助文档反馈 2.去掉页面末尾的 Edit this page
无
可提交文档问题意见反馈
无

fix: 1. 增加帮助文档反馈 2.去掉页面末尾的 Edit this page

---

docs/server/PHP SDK.md

php文档更新为1.0.1
更新api，依旧支持老版本的api
支持userKey设置
无
无
无

update: php版本更新1.0.1

---

docs/server/PHP SDK.md

fix: packagist地址

---

docs/server/Python SDK.md

添加 python sdk 说明

---

docs/other/Flutter SDK.md

update: FastGit 链接更新
访问 https://hub.fastgit.xyz/growingio/flutter-growingio-sdk-tracker-plugin.git 是否正常
无
参考: 
- https://fastgit.org/
- https://doc.fastgit.org/zh-cn/guide.html

update: FastGit 链接更新

---

docs/android/base/Getting Started.md
docs/ios/base/Getting_Started.md

- iOS/Android 集成添加「使用 GioKit 验证」相关描述
- 对应「无埋点集成」 / 「埋点集成」添加跳转链接
- 更新集成成功提示语中的版本号
无
无
无

update: iOS/Android 集成添加「使用 GioKit 验证」相关描述

---

docs/android/base/api.md
docs/ios/base/api.md
docs/miniprogram/commonlyApi.md
docs/other/Flutter SDK.md
docs/other/React Native.md
docs/server/Java SDK.md
docs/server/PHP SDK.md
docs/server/Python SDK.md
docs/webjs/base/api.md

增加各SDK埋点事件和用户属性事件到使用示例的链接
点击链接跳转到对应示例
埋点事件和用户属性事件调用示例
无

fix：增加各SDK埋点事件和用户属性事件到使用示例的链接

---

docs/android/base/Getting Started.md

更新android sdk的混淆规则

---

docs/android/base/Configuration.md
docs/android/base/Getting Started.md
docs/android/base/api.md
docs/android/develop/coutom sdk.md
docs/android/develop/custom module.md
docs/android/question.md
docs/android/version.md
docs/giokit/android/version.md
version_config.json

补充Android sdk 3.3.5版本记录

---

docs/miniprogram/commonlyApi.md

修复小程序与H5打通时getGioInfo的书写示例和部分提示
无
无
无

fix: 修改getGioInfo文档逻辑

---

docs/miniprogram/commonlyApi.md

add：增加微信用户属性设置和支付宝用户属性设置说明
小程序登录用户属性接口上报微信，支付宝用户信息
无

add：增加微信用户属性设置和支付宝用户属性设置说明

---

docs/miniprogram/3.8/integration/qq.md

fix: 修复qqsdk地址

---

docs/android/version.md
docs/basicknowledge/userModel.md
docs/giokit/android/version.md
docs/ios/version.md
question/common.md
version_config.json

1. iOS SDK 3.3.5 版本记录修改  2. 访问用户ID生成说明修改
无
iOS SDK 集成
无

fix：1. iOS SDK 3.3.5 版本记录修改  2. 访问用户ID生成说明修改

---

docs/compliance/webCompliance.md
docs/webjs/base/api.md
docs/webjs/version.md

add: Web JS SDK 3.3.10 发版记录和功能调整
帮助文档增加对应文案
Web JS SDK 的使用
无

Web  JS  SDK  3.3.10 发版记录和功能调整

---

docs/miniprogram/3.3/integration/alipay.md
docs/miniprogram/3.3/integration/wx.md

fix: 修复3.3文档中示例错误的问题

---

docs/webjs/base/api.md

移除web文档中部分api回调的内容，线上版本不存在回调
无
无
无

fix: 修复web文档内容

---

docs/webjs/version.md

补充 web js sdk 3.3.11版本记录

---

docs/ios/base/api.md
docs/ios/version.md
version_config.json

- feat: iOS SDK release 3.3.6
- CI 通过
无
无

feat: iOS SDK release 3.3.6

---

docs/android/base/Configuration.md
docs/android/base/api.md
docs/android/base/index.md
docs/android/develop/coutom sdk.md
docs/android/develop/custom module.md
docs/android/version.md
version_config.json

Android sdk 3.3.6发版

---

docs/miniprogram/3.8/integration/alipay.md
docs/miniprogram/3.8/integration/baidu.md
docs/miniprogram/3.8/integration/bytedance.md
docs/miniprogram/3.8/integration/qq.md
docs/miniprogram/3.8/integration/quickapp.md
docs/miniprogram/3.8/integration/taobao.md
docs/miniprogram/3.8/integration/wechat.md
docs/miniprogram/3.8/version.md

fix: 修复小程序3.8.0-rc.5 sdk地址

---

docs/miniprogram/3.8/commonlyApi.md
docs/miniprogram/3.8/integration/alipay.md
docs/miniprogram/3.8/integration/baidu.md
docs/miniprogram/3.8/integration/bytedance.md
docs/miniprogram/3.8/integration/qq.md
docs/miniprogram/3.8/integration/quickapp.md
docs/miniprogram/3.8/integration/taobao.md
docs/miniprogram/3.8/integration/wechat.md
docs/miniprogram/3.8/version.md

feat：完善部分api说明，发布3.8.0-rc.6

---

docs/android/base/api.md
docs/ios/base/api.md
docs/miniprogram/3.3/commonlyApi.md
docs/miniprogram/3.3/integration/wx.md
docs/miniprogram/3.8/commonlyApi.md
docs/miniprogram/3.8/integration/alipay.md
docs/miniprogram/3.8/integration/wechat.md
docs/other/Flutter SDK.md
docs/other/React Native.md
docs/webjs/base/api.md

小程序3.3 SDK Taro 增加框架说明
无
小程序SDK 3.3 Taro框架使用
无

fix:  小程序3.3 SDK Taro 增加框架

---

docs/miniprogram/3.3/integration/alipay.md
docs/miniprogram/3.3/integration/wx.md
docs/miniprogram/3.8/commonlyApi.md
docs/miniprogram/3.8/integration/alipay.md
docs/miniprogram/3.8/integration/baidu.md
docs/miniprogram/3.8/integration/bytedance.md
docs/miniprogram/3.8/integration/qq.md
docs/miniprogram/3.8/integration/quickapp.md
docs/miniprogram/3.8/integration/taobao.md
docs/miniprogram/3.8/integration/wechat.md
docs/miniprogram/3.8/upgrade.md
docs/server/Java SDK.md
docs/webjs/base/api.md
docs/webjs/base/configuration.md

fix: 1. 微信小程序添加白名增加第三方平台设置说明
2. 小程序SDK示例代码host 地址提示修改
小程序SDK使用
无

微信小程序添加白名增加第三方平台设置说明

---

docs/miniprogram/3.3/version.md

fix：修改3.3.8发版日期

---

docs/giokit/ios/version.md

add: iOS GioKit 1.0.6 版本更新
无
无
无

add: iOS GioKit 1.0.6 版本更新

---

docs/ios/version.md

feat: release iOS SDK 3.4.0
无
无
无

feat: release iOS SDK 3.4.0

---

docs/compliance/compliance.md

合规指南中增加中华人民共和国民法典

---

docs/Measurement Protocol.md
docs/miniprogram/3.3/integration/alipay.md
docs/miniprogram/3.3/integration/wx.md

fix：1. 增加 enableEventStore 使用提醒
2. 测量协议用户属性示例修改
无
无
无

增加 enableEventStore 使用提醒

---

docs/webjs/version.md

增加 Web JS SDK 3.3.15 发版记录
无
Web JS SDK 使用
无

增加 Web JS SDK 3.3.15 发版记录

---

docs/miniprogram/3.3/version.md

feat: 小程序3.3.10发布

---

docs/Measurement Protocol.md
docs/miniprogram/3.8/integration/alipay.md
docs/miniprogram/3.8/integration/baidu.md
docs/miniprogram/3.8/integration/bytedance.md
docs/miniprogram/3.8/integration/kuaishou.md
docs/miniprogram/3.8/integration/qq.md
docs/miniprogram/3.8/integration/quickapp.md
docs/miniprogram/3.8/integration/taobao.md
docs/miniprogram/3.8/integration/wechat.md
docs/miniprogram/3.8/version.md

feat: 小程序发布3.8.4

---

docs/miniprogram/3.3/version.md
docs/miniprogram/3.8/version.md

Minp1 优化version

---

docs/android/version.md
docs/ios/version.md
version_config.json

add：增加 iOS 3.4.2 发版记录

---

docs/android/base/Configuration.md

修改Android SDK 注册Protobuf模块示例代码
无
无
无

 修改Android SDK 注册Protobuf模块示例代码

---

docs/android/base/Configuration.md
docs/ios/base/Configuration.md
docs/miniprogram/3.3/commonlyApi.md
docs/miniprogram/3.8/commonlyApi.md

添加H5页面与APP，小程序用户数据打通效果说明
无
无
无

添加H5页面与APP，小程序用户数据打通效果说明

---

docs/webjs/3.8/version.md

feat: 发布web3.8.0-rc.3

---

docs/webjs/3.8/version.md

fix: 发布web3.8.0-rc.4

---

docs/ios/version.md
version_config.json

- feat: iOS release 3.4.3
无
无
无

feat: iOS release 3.4.3

---

docs/ios/base/api.md
docs/ios/version.md

- docs: iOS SDK track timer
无
无
无

docs: iOS SDK track timer

---

blog/2022-10-13-custom ios sdk.md

- docs: blog 添加 truncate 截断标志
- CI 通过
无
无

docs: blog 添加 truncate 截断标志

---

docs/giokit/ios/integrate.md
docs/giokit/ios/version.md

- feat: release iOS GioKit 1.1.0
- CI 通过
- iOS GioKit 1.1.0 发版
无

feat: release iOS GioKit 1.1.0

---

docs/ios/version.md

* fix: iOS SDK 版本记录显示异常
* CI 通过
* iOS SDK 版本记录
无

fix: iOS SDK 版本记录显示异常

---

docs/webjs/3.8/version.md

feat: 更新web发版记录

---

docs/giokit/ios/version.md
docs/ios/api.md
docs/ios/version.md
version_config.json

* docs: release iOS SDK 3.4.6, iOS GioKit 1.1.1
* CI 通过
* release iOS SDK 3.4.6, iOS GioKit 1.1.1
无

docs: release iOS SDK 3.4.6, iOS GioKit 1.1.1

---

docs/android/Introduce.md
docs/android/PlatformBom.md
docs/android/api.md
docs/android/modules/adapter module.md
docs/android/modules/advert module.md
docs/android/modules/circler module.md
docs/android/modules/core module.md
docs/android/modules/debugger module.md
docs/android/modules/encoder module.md
docs/android/modules/hybrid module.md
docs/android/modules/oaid module.md
docs/android/modules/protobuf module.md
docs/android/version.md
version_config.json

release Android sdk 3.4.5

---

docs/android/Introduce.md
version_config.json

plugin  3.4.5

---

docs/android/api.md
docs/ios/api.md
docs/miniprogram/3.8/integration/alipay.md
docs/miniprogram/3.8/integration/baidu.md
docs/miniprogram/3.8/integration/bytedance.md
docs/miniprogram/3.8/integration/kuaishou.md
docs/miniprogram/3.8/integration/qq.md
docs/miniprogram/3.8/integration/quickapp.md
docs/miniprogram/3.8/integration/taobao.md
docs/miniprogram/3.8/integration/wechat.md
docs/miniprogram/3.8/plugins/compress.md
docs/miniprogram/3.8/plugins/eventAutoTracking.md
docs/miniprogram/3.8/plugins/impressionTracking.md
docs/miniprogram/3.8/plugins/index.md
docs/miniprogram/3.8/plugins/multiIntegrate.md
docs/miniprogram/3.8/plugins/performance.md
docs/miniprogram/3.8/version.md

fix: 修复发布版本

---

docs/giokit/android/integrate.md

fix:giokit mistakens

---

docs/server/Java SDK.md

docs: 更新java sdk版本

---

docs/ios/Introduce.md

修改 SwiftPM 集成描述，从 master 改为对应的 version，避免由于 PR 合并导致用户所集成的版本随机

docs: 修改 SwiftPM 集成描述

---

docs/server/Java SDK.md
docs/webjs/3.3/api.md
docs/webjs/3.8/commonlyApi.md

java sdk发版1.0.14-cdp
修正web eventDuration字段为event_duration

feat: release java 1.0.14-cdp

---

docs/android/Introduce.md
docs/framework/flutter/Flutter Aspect.md
docs/framework/flutter/Flutter SDK.md
docs/ios/Introduce.md

* 添加 flutter 3.13.2 frontend server snapshot 
* 优化 flutter 集成说明，添加 Android 依赖步骤

feat: add flutter 3.13.2 support

---

docs/Measurement Protocol.md
docs/framework/flutter/Flutter SDK.md
docs/framework/flutter/index.md

docs: update Flutter SDK version

---

docs/android/AGP7.md
docusaurus.config.js

fix:修正 v3 文档的地址

---

docs/server/Java SDK.md

fix: sendTime is not supported in saas

---

docs/android/AGP7.md
docs/android/Configuration.md
docs/android/PlatformBom.md
docs/android/api.md
docs/android/modules/abtest module.md
docs/android/modules/core module.md
docs/android/modules/index.md
docs/android/version.md
docs/framework/harmonyos/index.md
docs/giokit/android/integrate.md
docs/giokit/android/version.md
docs/ios/version.md
github_version_fetch.py
knowledge/compliance/harmonyosCompliance.md
version_config.json

feat:添加 V4 新功能文档。

---

docs/android/modules/index.md
docs/android/modules/platform module.md

feat: add platform module

---

docs/android/AGP7.md
docs/android/Introduce.md

plugin upgrade

---

docs/framework/harmonyos/api.md

docs(ohos): sub tracker init

---

docs/android/Introduce.md
docs/android/PlatformBom.md
docs/android/modules/abtest module.md
docs/android/modules/adapter module.md
docs/android/modules/advert module.md
docs/android/modules/circler module.md
docs/android/modules/core module.md
docs/android/modules/debugger module.md
docs/android/modules/encoder module.md
docs/android/modules/flutter module.md
docs/android/modules/hybrid module.md
docs/android/modules/json module.md
docs/android/modules/oaid module.md
docs/android/modules/platform module.md
docs/android/upgrade/index.md
docs/android/version.md
docs/ios/version.md
version_config.json

doc: android v4.3.1 版本记录

---

docs/framework/harmonyos/Configuration.md
docs/framework/harmonyos/Introduce.md
docs/framework/harmonyos/_category_.json
docs/framework/harmonyos/api.md
docs/framework/harmonyos/index.md
docs/framework/harmonyos/version.md
docs/giokit/harmonyos/_category_.json
docs/giokit/harmonyos/index.md
docs/giokit/harmonyos/integrate.md
docs/giokit/harmonyos/version.md
knowledge/compliance/harmonyosCompliance.md
knowledge/debugverify/debug.md

更新 HarmonyOS NEXT SDK 2.0.0 对应文档

docs(harmonyos): update docs

---

docs/server/Java SDK.md

更新 Java SDK 文档，版本更新为1.0.16-cdp
无
无
无

docs: update the document of the Java SDK

---

docs/android/upgrade/index.md
docs/ios/upgrade/index.md

docs: update upgrade info

---

docs/SDK OVERVIEW.md
docs/android/modules/hybrid module.md
docs/ios/modules/Hybrid Module.md

docs: update introduction

---

knowledge/Measurement Protocol.md

docs: update protocol

---

docs/android/modules/advert module.md
docs/ios/modules/Ads Module.md

fix:去除平台的链接

---

docs/android/version.md
docs/index/android.md
github_version_fetch.py

build: update version_fectch script

---

docs/android/version.md
github_version_fetch.py

fix: compliance

---

docs/miniprogram/initSettings.md
docs/miniprogram/integration/alipay.md
docs/miniprogram/integration/baidu.md
docs/miniprogram/integration/bytedance.md
docs/miniprogram/integration/jingdong.md
docs/miniprogram/integration/kuaishou.md
docs/miniprogram/integration/qq.md
docs/miniprogram/integration/quickapp.md
docs/miniprogram/integration/taobao.md
docs/miniprogram/integration/wechat.md
docs/miniprogram/plugins/abtest.md
docs/miniprogram/plugins/compress.md
docs/miniprogram/plugins/eventAutoTracking.md
docs/miniprogram/plugins/impressionTracking.md
docs/miniprogram/plugins/index.md
docs/miniprogram/plugins/multipleInstances.md
docs/miniprogram/version.md

feat: 发布小程序4.3.2

---

knowledge/compliance/androidCompliance.md
knowledge/compliance/iosCompliance.md

建议客户在启动时优先初始化SDK，后续同意隐私政策通过采集开关来开启数据采集

feat: SDK 初始化建议

---

docs/server/Java SDK.md

更新Java SDK版本1.0.18-cdp
🐞 修复：
1. IDE Plugin开发时，无法找到对应配置文件
2. 默认网络请求地址异常问题
📝 Feature
3. 支持ab请求

feat: java 1.0.18-cdp

---

docs/server/Java SDK.md

docs: update java docs

---

docs/android/Introduce.md
docs/android/PlatformBom.md
docs/android/modules/abtest module.md
docs/android/modules/adapter module.md
docs/android/modules/advert module.md
docs/android/modules/apm module.md
docs/android/modules/circler module.md
docs/android/modules/compose module.md
docs/android/modules/core module.md
docs/android/modules/debugger module.md
docs/android/modules/encoder module.md
docs/android/modules/flutter module.md
docs/android/modules/hybrid module.md
docs/android/modules/json module.md
docs/android/modules/oaid module.md
docs/android/modules/platform module.md
docs/android/upgrade/index.md
docs/android/version.md
docs/ios/modules/ABTesting Module.md
docs/ios/modules/APM Module.md
version_config.json

* 添加 iOS SDK APM 模块源码地址
* 添加 Android SDK APM 模块使用文档

docs: update apm module desc

---

docs/framework/flutter/Flutter SDK.md
docs/framework/flutter/index.md

docs: upgrade flutter version
